language: java
sudo: false

install: true

jdk:
  - openjdk14


env:
  global:
    - CODECOV_TOKEN="671f5431-b3c4-481f-a794-af4ea82af889"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

services:
  - postgresql

before_script:
  - psql -c 'create database forum;' -U postgres

script:
  # - mvn test -B
  - mvn clean package -DskipTests=true

notifications:
  email:
    recipients:
      -aynuuu@gmail.ru
    on_success: never # default: change
    on_failure: always # default: always

deploy:
  provider: heroku
    api_key:
      secure: OBlqyRRYBa7mNJtp1f3prPnHWfqUTultTKWkRmnFtrNec1uKa5Z6ckR8eRW/ZKT4t22g95Afz2cr7TLNHUQG3H1L0UYAQ+hi16J7ZlqL7SzIrH50D5905kLm+2rt9nd5tGTUnZLEDSQKm0Pu8n32qXJeW2px6jUlD+WuzntR2m7G6Uu7isMB/B6/SoKVJMpKRjGEgVlsfkiaHK9zn6GjOyw3NlUDtoSRUMf2K4KdlOHkA3jdyoc0ZKlUQ9hcK5pCybFk5NA4yZj6Ed+Pb2dmvcmx09JQbHFBO45Xq8d+wtgjKY3Y5k5vqvrWQrfQ+897xKUnP6W4PvKIC6D/+5FO4oaNjDsdspKwiATO7R4AqAJfl/MHiA+YIKwyEWHNoIf8QgmtW3yCkBGnWaXkPMHxJXrlyu+jMtlzJR0ixzJDMXbZIVx8VDn1FO5QzeaWss4DNMjTbL1OI/xyrXws1ahu9mXXm9rdh9q+uf/OcWOmVe7pPNG3TwzBMYl2xq0u/Tf3JxEZvNNwI13UDAXPiyLiHN/6PFlbg9DeH3YYcj9HuATp7VQ6VsmN3YMeB2EF7ouc8Tc1KX1a3uVu/CzJcBZy2gaIy1bL2rchJ0ds5jawsUzWflyC54otYqra6paBUaDMS0Q9Y6oup4a2IIEKQjNjF+CakP09wMppsfzcfAG9sOM=
    app: infinite-castle-76604