language: java
sudo: false
install: true
jdk: openjdk14
env:
  global:
  - CODECOV_TOKEN="671f5431-b3c4-481f-a794-af4ea82af889"
after_success: bash <(curl -s https://codecov.io/bash)
services: postgresql
before_script: psql -c 'create database forum;' -U postgres
script: mvn clean package -DskipTests=true
notifications:
  email:
    recipients: aynuuu@gmail.ru
    on_success: never
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: wXg+0ucFBvt8NRch238Clspo9pUZii9IjWqr+jJlXDyjb0KuONXPaCe3JMn7WPPZ3JWpx86rav9y/y9Pl93pInvdCTHkk6I3bRjWZVqZxRrAyHAMy1xLPgMBZI+YrAY3AAyVdoGYZvFbe1R1Ey8Ao2wjEVp0RAc1eWEND6Yx1Fsj10p+djpg3q6O/uD6ivAswmLc0hyHKTPe38CSS6ZvL36WKGrY5fSCZ3rNe+5bvoeaAbT8Sczo/PTO4fSWt6HnLZBjUCdDEnRFaa5An1pFd0H/XA9Kh3Z1Br8Xv3C1RXvFXXpihnvCZUAOd6OgXyKFwkIfk0+Ly4Vsm0RJ2ujJQtUX3oBwGkKmqHrl0FcL5q73mkDFahR9M2yL1E8yOeELN68mE3lQ5uWTup8GilQVoJMT8Cx7RMQcodRxxO4j8tOctrkE8xwYDrijRVRHQU5Q69UQRGEF8d0RhWTGvXG/GKsdY5eradXmvIKLPYsrtvkWgh8KaMOSuUHXUEKlkfeljek40k+heVV0p2nCtpU2LpEQwt7LyCn3SS6HTJRqhvytqB6pRePQY5fgtLaRk4UBkjkFkVz++JNIoaCQTlI6b8Tfn7kHlEcPt6+xed5vZbavyPKhen6o2ZlTT7R97pRRtefsouOnKHIpQAzD069ZQP6kshkVe2XdFcfdl+zgPyI=
  app: infinite-castle-76604
