language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="671f5431-b3c4-481f-a794-af4ea82af889"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

services:
  - postgresql

before_script:
  - psql -c 'create database forum;' -U postgres
  - psql -U postgres -d forum -a -f db/schema.sql

script:
  - mvn test -B

notifications:
  email:
    recipients:
      -aynuuu@gmail.ru
    on_success: never # default: change
    on_failure: always # default: always